CREATE TYPE "car_instances_status" AS ENUM (
  'available',
  'sold'
);

CREATE TYPE "driver_categorys" AS ENUM (
  'A',
  'A1',
  'B',
  'B1',
  'BE',
  'C',
  'CE',
  'C1',
  'C1E',
  'D',
  'D1',
  'DE',
  'D1E',
  'M',
  'Tm',
  'Tb'
);

CREATE TYPE "type_discount" AS ENUM (
  'price',
  'percent',
  'object'
);

CREATE TYPE "status_social_programs_promotions" AS ENUM (
  'active',
  'not_active'
);

CREATE TYPE "order_status" AS ENUM (
  'new',
  'processing',
  'completed',
  'canceled'
);

CREATE TYPE "sale_contract_status" AS ENUM (
  'draft',
  'signed',
  'canceled'
);

CREATE TABLE "brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "country" text NOT NULL
);

CREATE TABLE "classes_cars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class" varchar(25) NOT NULL
);

CREATE TABLE "drive_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(25) NOT NULL
);

CREATE TABLE "car_body_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "fuel_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL
);

CREATE TABLE "engines" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_engine" text NOT NULL
);

CREATE TABLE "positions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "position" text NOT NULL
);

CREATE TABLE "labor_rates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rate" text NOT NULL
);

CREATE TABLE "order_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(50) NOT NULL
);

CREATE TABLE "telephone_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL
);

CREATE TABLE "car_models" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand_id" int NOT NULL,
  "class_id" int NOT NULL,
  "drive_type_id" int NOT NULL,
  "car_body_type_id" int NOT NULL,
  "name_configuration" text NOT NULL,
  "model_name" text NOT NULL,
  "year" int NOT NULL,
  "is_orderable" boolean NOT NULL DEFAULT true
);

CREATE TABLE "additional_equipment_car" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "price" decimal(12,2) DEFAULT null
);

CREATE TABLE "social_programs_promotions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "type" type_discount NOT NULL,
  "discount_size" varchar(255),
  "status" status_social_programs_promotions,
  "comment" text
);

CREATE TABLE "warehouses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "street" text NOT NULL,
  "total_number_places_warehouse" int NOT NULL,
  "number_free_spaces_warehouse" int
);

CREATE TABLE "insurance_policies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_number" varchar(50) UNIQUE NOT NULL,
  "insurer_name" varchar(100) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "premium_amount" decimal(10,2) NOT NULL,
  "coverage_details" text
);

CREATE TABLE "human" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "surname" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "patronymic" varchar(255) NOT NULL,
  "date_birth" date NOT NULL,
  "serial_passport" int NOT NULL,
  "number_passport" int NOT NULL,
  "issued_passport" text NOT NULL,
  "number_department" int NOT NULL,
  "place_registration" text NOT NULL,
  "place_residence" text
);

CREATE TABLE "clients" (
  "human_id" int PRIMARY KEY,
  "number_visits" int
);

CREATE TABLE "staff" (
  "human_id" int PRIMARY KEY,
  "education" text NOT NULL,
  "position_id" int NOT NULL,
  "telephone" text NOT NULL,
  "salary" int NOT NULL,
  "labor_rate_id" int NOT NULL,
  "hire_date" date NOT NULL,
  "dismissal_date" date
);

CREATE TABLE "car_order_colors" (
  "car_models_id" int,
  "color" text,
  "is_available" boolean NOT NULL,
  PRIMARY KEY ("car_models_id", "color")
);

CREATE TABLE "list_fuel_types_engines" (
  "fuel_type_id" int,
  "engines_id" int,
  PRIMARY KEY ("fuel_type_id", "engines_id")
);

CREATE TABLE "list_car_models_engines" (
  "car_models_id" int,
  "engines_id" int,
  PRIMARY KEY ("car_models_id", "engines_id")
);

CREATE TABLE "list_additional_equipment_cars" (
  "car_instance_id" int,
  "aec_id" int,
  PRIMARY KEY ("car_instance_id", "aec_id")
);

CREATE TABLE "list_social_programs_promotions" (
  "car_instance_id" int,
  "social_programs_promotion_id" int,
  PRIMARY KEY ("car_instance_id", "social_programs_promotion_id")
);

CREATE TABLE "telephone_number" (
  "human_id" int,
  "telephone_type_id" int,
  "telephone" int NOT NULL,
  PRIMARY KEY ("human_id", "telephone_type_id")
);

CREATE TABLE "car_instances" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_id" int NOT NULL,
  "warehouses_id" int NOT NULL,
  "insurance_policies_id" int,
  "vin" varchar(17) UNIQUE NOT NULL,
  "engine_number" varchar(21) UNIQUE NOT NULL,
  "mileage" int NOT NULL,
  "driver_category" driver_categorys NOT NULL,
  "status" car_instances_status NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_DATE
);

CREATE TABLE "car_orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int NOT NULL,
  "car_instance_id" int,
  "order_date" date NOT NULL DEFAULT CURRENT_DATE,
  "status" order_status NOT NULL DEFAULT 'new',
  "total_price" decimal(10,2),
  "comments" text
);

CREATE TABLE "sales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_instance_id" int NOT NULL,
  "client_id" int NOT NULL,
  "staff_id" int,
  "sale_date" date NOT NULL,
  "price" decimal(12,2) NOT NULL,
  "comments" text
);

CREATE TABLE "sale_contracts" (
  "sales_id" int PRIMARY KEY,
  "order_id" int,
  "contract_number" varchar(50) UNIQUE NOT NULL,
  "contract_date" date NOT NULL,
  "total_price" decimal(10,2) NOT NULL,
  "file_link" varchar(255),
  "status" sale_contract_status DEFAULT 'signed',
  "comments" text
);

CREATE TABLE "staff_orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" int NOT NULL,
  "order_type" int NOT NULL,
  "order_date" date NOT NULL,
  "description" text,
  "document_link" varchar(255)
);

ALTER TABLE "car_models" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id");

ALTER TABLE "car_models" ADD FOREIGN KEY ("class_id") REFERENCES "classes_cars" ("id");

ALTER TABLE "car_models" ADD FOREIGN KEY ("drive_type_id") REFERENCES "drive_types" ("id");

ALTER TABLE "car_models" ADD FOREIGN KEY ("car_body_type_id") REFERENCES "car_body_types" ("id");

ALTER TABLE "clients" ADD FOREIGN KEY ("human_id") REFERENCES "human" ("id");

ALTER TABLE "staff" ADD FOREIGN KEY ("human_id") REFERENCES "human" ("id");

ALTER TABLE "staff" ADD FOREIGN KEY ("position_id") REFERENCES "positions" ("id");

ALTER TABLE "staff" ADD FOREIGN KEY ("labor_rate_id") REFERENCES "labor_rates" ("id");

ALTER TABLE "car_order_colors" ADD FOREIGN KEY ("car_models_id") REFERENCES "car_models" ("id");

ALTER TABLE "list_fuel_types_engines" ADD FOREIGN KEY ("fuel_type_id") REFERENCES "fuel_types" ("id");

ALTER TABLE "list_fuel_types_engines" ADD FOREIGN KEY ("engines_id") REFERENCES "engines" ("id");

ALTER TABLE "list_car_models_engines" ADD FOREIGN KEY ("car_models_id") REFERENCES "car_models" ("id");

ALTER TABLE "list_car_models_engines" ADD FOREIGN KEY ("engines_id") REFERENCES "engines" ("id");

ALTER TABLE "list_additional_equipment_cars" ADD FOREIGN KEY ("car_instance_id") REFERENCES "car_instances" ("id");

ALTER TABLE "list_additional_equipment_cars" ADD FOREIGN KEY ("aec_id") REFERENCES "additional_equipment_car" ("id");

ALTER TABLE "list_social_programs_promotions" ADD FOREIGN KEY ("car_instance_id") REFERENCES "car_instances" ("id");

ALTER TABLE "list_social_programs_promotions" ADD FOREIGN KEY ("social_programs_promotion_id") REFERENCES "social_programs_promotions" ("id");

ALTER TABLE "telephone_number" ADD FOREIGN KEY ("human_id") REFERENCES "human" ("id");

ALTER TABLE "telephone_number" ADD FOREIGN KEY ("telephone_type_id") REFERENCES "telephone_type" ("id");

ALTER TABLE "car_instances" ADD FOREIGN KEY ("model_id") REFERENCES "car_models" ("id");

ALTER TABLE "car_instances" ADD FOREIGN KEY ("warehouses_id") REFERENCES "warehouses" ("id");

ALTER TABLE "car_instances" ADD FOREIGN KEY ("insurance_policies_id") REFERENCES "insurance_policies" ("id");

ALTER TABLE "car_orders" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("human_id");

ALTER TABLE "car_orders" ADD FOREIGN KEY ("car_instance_id") REFERENCES "car_instances" ("id");

ALTER TABLE "sales" ADD FOREIGN KEY ("car_instance_id") REFERENCES "car_instances" ("id");

ALTER TABLE "sales" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("human_id");

ALTER TABLE "sales" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("human_id");

ALTER TABLE "sale_contracts" ADD FOREIGN KEY ("sales_id") REFERENCES "sales" ("id");

ALTER TABLE "sale_contracts" ADD FOREIGN KEY ("order_id") REFERENCES "car_orders" ("id");

ALTER TABLE "staff_orders" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("human_id");

ALTER TABLE "staff_orders" ADD FOREIGN KEY ("order_type") REFERENCES "order_types" ("id");
